repos:
- hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
- hooks:
  - id: isort
    args: ["--profile", "black"]
    name: isort (python)
  repo: https://github.com/pycqa/isort
  rev: 5.10.1
- hooks:
  - id: yapf
    name: yapf
    additional_dependencies: [toml]
    args: [--style, google]
  repo: https://github.com/pre-commit/mirrors-yapf
  rev: v0.32.0
- hooks:
  - id: commitizen
    stages:
    - commit-msg
  repo: https://github.com/commitizen-tools/commitizen
  rev: v2.32.7
