name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Quality:
    uses: MedVisBonn/eyepy/.github/workflows/_quality.yaml@master

  Release:
    needs: Quality
    uses: MedVisBonn/eyepy/.github/workflows/_release.yaml@master
    secrets:
      PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}

  Documentation:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install \
              mkdocs-material \
              mkdocstrings[python] \
              mkdocs-gen-files \
              mkdocs-literate-nav \
              mkdocs-section-index \
              pymdown-extensions
      - run: mkdocs gh-deploy --force
